name: como usar variaveis de ambiente
on:
  workflow_dispatch:
env:
  ENV_VALOR_WORKFLOW: "valor WORKFLOW"
jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "valor JOB teste-env"
    steps:
      - name: Execucao
        env:
          ENV_ACTION: "valor ACTION - Execucao"
        run: |
          echo "$ENV_VALOR_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
